---

- hosts: localhost

# API Call using Ansible URI Module against api.covid19tracker.ca/reports #
  tasks:
    - name: GET Canada COVID 19 report
      uri:
        url: https://api.covid19tracker.ca/reports
        method: GET
        headers: 
          Connection: keep-alive
          Accept: application/json 
        return_content: yes
        validate_certs: no
        follow_redirects: yes
      register: report

# Nested Loop over JSON response and capture report info #
    - name: "Get Report Info"
      debug:
        var: item
      with_nested: 
        - "{{ report.json | json_query('data[*].date') }}"
      register: report_loop_output

    - debug:
        msg: " {{ report_loop_output }} "

# Create CSV file with results #
    - name: Create CSV
      copy: content="{{ report_loop_output | json_query('results[*].item') }}" dest=../reports/csv/report.csv

# Format CSV #
    - name: Format CSV File New Lines
      replace:
        path: ../reports/csv/report.csv
        regexp: '],'
        replace: ']\n'

# Format CSV #
    - name: Format CSV File Clean Up
      replace:
        path: ../reports/csv/report.csv
        regexp: '\[|\]|"'
        replace: ''

# Add Header Row to CSV #
    - name: Header Row
      lineinfile:
        path: ../reports/csv/report.csv
        insertbefore: BOF
        line: Date, Change Cases, Change Fatalities, Change Tests, Change Hospitalizations, Change Criticals, Change Recoveries, Total Cases, Total Fatalities, Total Tests, Total Criticals, Total Recoveries

# Create Markdown file with results # 
    - name: Create Markdown
      copy: content="{{ report_loop_output | json_query('results[*].item') }}" dest=../reports/markdown/report.md

# Format Markdown #
    - name: Format Markdown File New Lines
      replace:
        path: ../reports/markdown/report.md
        regexp: '],'
        replace: ']\n'

# Format Markdown #
    - name: Format Markdown File Clean Up
      replace:
        path: ../reports/markdown/report.md
        regexp: '\[|\]|"'
        replace: ''      

# Format Markdown #
    - name: Format Markdown File Commas to Pipes
      replace:
        path: ../reports/markdown/report.md
        regexp: ','
        replace: ' | '

# Add Header Rows to Markdown #
    - name: Header Row
      lineinfile:
        path: ../reports/markdown/report.md
        insertbefore: BOF
        line: "{{ item.property }}"
      with_items:
        - { property: '| ---- | ------------ | ----------------- | ------------ | ----------------------- | ---------------- | ----------------- | ----------- | ---------------- | ----------- | --------------- | ---------------- |' }
        - { property: '| Date | Change Cases | Change Fatalities | Change Tests | Change Hospitalizations | Change Criticals | Change Recoveries | Total Cases | Total Fatalities | Total Tests | Total Criticals | Total Recoveries |' }

# Create Mind Map # 
    - name: create Report Mind Map 
      shell: "markmap --no-open ../reports/markdown/report.md -o ../reports/mindmap/report.html"
      register: markmap