---

- hosts: localhost

# API Call using Ansible URI Module against api.covid19tracker.ca/reports #
  tasks:
    - name: GET Canada COVID 19 report
      uri:
        url: https://api.covid19tracker.ca/reports
        method: GET
        headers: 
          Connection: keep-alive
          Accept: application/json 
        return_content: yes
        validate_certs: no
        follow_redirects: yes
      register: report

    - debug:
        msg: "{{ report }}"
